-- FinAnalytics production schema
-- Run with Supabase CLI (`supabase db push`) or paste into the SQL Editor once.

create type public.company_role as enum ('owner', 'admin', 'editor', 'viewer');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.companies (
  id bigint primary key generated by default as identity,
  name_th text not null,
  name_en text not null,
  currency text not null default 'THB' check (currency ~ '^[A-Z]{3}$'),
  type text not null default 'parent' check (type in ('parent', 'subsidiary')),
  industry text not null,
  group_id text,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_members (
  company_id bigint not null references public.companies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.company_role not null default 'viewer',
  created_at timestamptz not null default now(),
  primary key (company_id, user_id)
);

create table public.financial_records (
  id bigint primary key generated always as identity,
  company_id bigint not null references public.companies(id) on delete cascade,
  year integer not null check (year between 2000 and 2200),
  month integer not null check (month between 1 and 12),
  revenue numeric(20,2) not null default 0,
  expense numeric(20,2) not null default 0,
  cash_in numeric(20,2) not null default 0,
  cash_out numeric(20,2) not null default 0,
  loan_balance numeric(20,2) not null default 0,
  status text not null default 'draft' check (status in ('draft', 'closed')),
  created_by uuid default auth.uid() references auth.users(id),
  updated_by uuid default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, year, month)
);

create table public.exchange_rates (
  id bigint primary key generated always as identity,
  currency text not null check (currency ~ '^[A-Z]{3}$' and currency <> 'THB'),
  rate_to_thb numeric(20,8) not null check (rate_to_thb > 0),
  effective_date date not null,
  created_by uuid default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(currency, effective_date)
);

create table public.audit_log (
  id bigint primary key generated always as identity,
  table_name text not null,
  record_id text,
  company_id bigint references public.companies(id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  created_at timestamptz not null default now()
);

create index financial_records_company_year_idx on public.financial_records(company_id, year);
create index company_members_user_idx on public.company_members(user_id);
create index audit_log_company_created_idx on public.audit_log(company_id, created_at desc);
create index exchange_rates_currency_date_idx on public.exchange_rates(currency, effective_date desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    updated_at = now();
  return new;
end;
$$;

create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, full_name)
select id, coalesce(email, ''), raw_user_meta_data ->> 'full_name'
from auth.users
on conflict (id) do nothing;

create or replace function public.is_company_member(target_company_id bigint)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.company_members
    where company_id = target_company_id and user_id = (select auth.uid())
  );
$$;

create or replace function public.has_company_role(target_company_id bigint, allowed_roles public.company_role[])
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.company_members
    where company_id = target_company_id
      and user_id = (select auth.uid())
      and role = any(allowed_roles)
  );
$$;

create or replace function public.add_company_owner()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.company_members(company_id, user_id, role)
  values (new.id, new.created_by, 'owner')
  on conflict do nothing;
  return new;
end;
$$;

create trigger company_add_owner
after insert on public.companies
for each row execute function public.add_company_owner();

create or replace function public.set_record_actor()
returns trigger
language plpgsql set search_path = ''
as $$
begin
  new.updated_at = now();
  new.updated_by = (select auth.uid());
  if tg_op = 'INSERT' then
    new.created_by = coalesce(new.created_by, (select auth.uid()));
  end if;
  return new;
end;
$$;

create trigger financial_records_set_actor
before insert or update on public.financial_records
for each row execute function public.set_record_actor();

create or replace function public.write_audit_log()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  old_row jsonb;
  new_row jsonb;
  related_company_id bigint;
begin
  old_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  related_company_id := coalesce(
    nullif(new_row ->> 'company_id', '')::bigint,
    nullif(old_row ->> 'company_id', '')::bigint,
    case when tg_table_name = 'companies' then coalesce((new_row ->> 'id')::bigint, (old_row ->> 'id')::bigint) end
  );
  insert into public.audit_log (
    table_name, record_id, company_id, action, old_data, new_data,
    changed_by, changed_by_email
  ) values (
    tg_table_name,
    coalesce(new_row ->> 'id', old_row ->> 'id', new_row ->> 'user_id', old_row ->> 'user_id'),
    related_company_id,
    tg_op,
    old_row,
    new_row,
    (select auth.uid()),
    (select auth.jwt() ->> 'email')
  );
  return coalesce(new, old);
end;
$$;

create trigger audit_companies after insert or update or delete on public.companies
for each row execute function public.write_audit_log();
create trigger audit_company_members after insert or update or delete on public.company_members
for each row execute function public.write_audit_log();
create trigger audit_financial_records after insert or update or delete on public.financial_records
for each row execute function public.write_audit_log();
create trigger audit_exchange_rates after insert or update or delete on public.exchange_rates
for each row execute function public.write_audit_log();

create or replace function public.grant_company_access(
  target_company_id bigint,
  target_email text,
  target_role public.company_role
)
returns void
language plpgsql security definer set search_path = ''
as $$
declare target_user_id uuid;
begin
  if not public.has_company_role(target_company_id, array['owner','admin']::public.company_role[]) then
    raise exception 'Only owners and admins can grant access';
  end if;
  select id into target_user_id from public.profiles where lower(email) = lower(trim(target_email));
  if target_user_id is null then
    raise exception 'User must sign up before access can be granted';
  end if;
  if target_role = 'owner' and not public.has_company_role(target_company_id, array['owner']::public.company_role[]) then
    raise exception 'Only owners can grant owner access';
  end if;
  insert into public.company_members(company_id, user_id, role)
  values (target_company_id, target_user_id, target_role)
  on conflict (company_id, user_id) do update set role = excluded.role;
end;
$$;

create or replace function public.revoke_company_access(
  target_company_id bigint,
  target_user_id uuid
)
returns void
language plpgsql security definer set search_path = ''
as $$
declare target_role public.company_role;
begin
  if not public.has_company_role(target_company_id, array['owner','admin']::public.company_role[]) then
    raise exception 'Only owners and admins can revoke access';
  end if;
  select role into target_role from public.company_members
  where company_id = target_company_id and user_id = target_user_id;
  if target_role = 'owner' then
    raise exception 'Owner access cannot be revoked; transfer ownership first';
  end if;
  delete from public.company_members where company_id = target_company_id and user_id = target_user_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.company_members enable row level security;
alter table public.financial_records enable row level security;
alter table public.exchange_rates enable row level security;
alter table public.audit_log enable row level security;

create policy profiles_read_self_or_colleague on public.profiles for select to authenticated
using (
  id = (select auth.uid()) or exists (
    select 1 from public.company_members mine
    join public.company_members theirs on theirs.company_id = mine.company_id
    where mine.user_id = (select auth.uid()) and theirs.user_id = profiles.id
  )
);
create policy profiles_update_self on public.profiles for update to authenticated
using (id = (select auth.uid())) with check (id = (select auth.uid()));

create policy companies_read_member on public.companies for select to authenticated
using (public.is_company_member(id));
create policy companies_create_authenticated on public.companies for insert to authenticated
with check (created_by = (select auth.uid()));
create policy companies_update_admin on public.companies for update to authenticated
using (public.has_company_role(id, array['owner','admin']::public.company_role[]))
with check (public.has_company_role(id, array['owner','admin']::public.company_role[]));
create policy companies_delete_owner on public.companies for delete to authenticated
using (public.has_company_role(id, array['owner']::public.company_role[]));

create policy members_read_company on public.company_members for select to authenticated
using (public.is_company_member(company_id));

create policy records_read_member on public.financial_records for select to authenticated
using (public.is_company_member(company_id));
create policy records_create_editor on public.financial_records for insert to authenticated
with check (public.has_company_role(company_id, array['owner','admin','editor']::public.company_role[]));
create policy records_update_editor on public.financial_records for update to authenticated
using (public.has_company_role(company_id, array['owner','admin','editor']::public.company_role[]))
with check (public.has_company_role(company_id, array['owner','admin','editor']::public.company_role[]));
create policy records_delete_admin on public.financial_records for delete to authenticated
using (public.has_company_role(company_id, array['owner','admin']::public.company_role[]));

create policy rates_read_authenticated on public.exchange_rates for select to authenticated using (true);
create policy rates_write_admin on public.exchange_rates for all to authenticated
using (exists (
  select 1 from public.company_members
  where user_id = (select auth.uid()) and role in ('owner', 'admin')
))
with check (exists (
  select 1 from public.company_members
  where user_id = (select auth.uid()) and role in ('owner', 'admin')
));

create policy audit_read_member on public.audit_log for select to authenticated
using (company_id is null or public.is_company_member(company_id));

revoke all on public.audit_log from anon, authenticated;
grant select on public.audit_log to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.companies to authenticated;
grant select on public.company_members to authenticated;
grant select, insert, update, delete on public.financial_records to authenticated;
grant select, insert, update, delete on public.exchange_rates to authenticated;
grant execute on function public.grant_company_access(bigint, text, public.company_role) to authenticated;
grant execute on function public.revoke_company_access(bigint, uuid) to authenticated;

-- Seed demo companies after creating your first Auth user:
-- Replace FIRST_USER_UUID below, then run the block once.
-- insert into public.companies (id, name_th, name_en, currency, type, industry, group_id, created_by) values
-- (1, 'บริษัท อัลฟา จำกัด', 'Alpha Co., Ltd.', 'THB', 'parent', 'retail', 'alpha', 'FIRST_USER_UUID'),
-- (2, 'บริษัท เบต้า จำกัด', 'Beta Co., Ltd.', 'USD', 'subsidiary', 'retail', 'alpha', 'FIRST_USER_UUID'),
-- (3, 'บริษัท แกมมา จำกัด', 'Gamma Co., Ltd.', 'THB', 'subsidiary', 'manufacturing', 'alpha', 'FIRST_USER_UUID'),
-- (4, 'บริษัท เดลต้า จำกัด', 'Delta Co., Ltd.', 'THB', 'parent', 'tech', 'delta', 'FIRST_USER_UUID'),
-- (5, 'บริษัท เอปไซลอน จำกัด', 'Epsilon Co., Ltd.', 'THB', 'subsidiary', 'service', 'delta', 'FIRST_USER_UUID');
