-- FinAnalytics / AccountX4 v1.9.1
-- Dashboard / Export Readiness Gate
-- Safe/idempotent: adds batch-level readiness state, snapshot metadata,
-- and delete policies required to re-run validation without duplicating stale results.

begin;

alter table public.import_batches
  add column if not exists readiness_status text default 'not_validated',
  add column if not exists readiness_score integer,
  add column if not exists dashboard_ready boolean default false,
  add column if not exists export_ready boolean default false,
  add column if not exists external_use_ready boolean default false,
  add column if not exists validation_summary jsonb default '{}'::jsonb,
  add column if not exists last_validated_at timestamptz,
  add column if not exists export_warning_ack_required boolean default false;

create index if not exists idx_import_batches_readiness
  on public.import_batches(company_id, fiscal_year, period, period_type, statement_scope, readiness_status, export_ready);

alter table public.financial_metrics_snapshots
  add column if not exists readiness_status text default 'not_validated',
  add column if not exists readiness_score integer;

create index if not exists idx_financial_metrics_snapshots_readiness
  on public.financial_metrics_snapshots(company_id, import_batch_id, readiness_status, readiness_score);

-- Rebuild requires replacing stale validation/snapshot rows. Keep policies scoped to company members.
do $$ begin
  create policy validation_results_delete on public.validation_results
    for delete to authenticated using (company_id is null or public.is_company_member(company_id));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy financial_metrics_snapshots_delete on public.financial_metrics_snapshots
    for delete to authenticated using (public.is_company_member(company_id));
exception when duplicate_object then null; end $$;

-- Optional stricter status documentation. Not using a check constraint here to avoid breaking older rows.
comment on column public.import_batches.readiness_status is
  'v1.9.1 gate: not_validated, not_ready, mapping_review_required, dashboard_ready, export_ready, external_use_ready';
comment on column public.import_batches.validation_summary is
  'JSON summary generated by the Accounting Engine. Used by Data Quality, Import History and Export Center.';

commit;
